work_dir: ./work_dir/recognition/tag/STGCN_C4_processed_semTA_TAG_softselector_routeA_finetune_ballAnchor_smooth
label_smoothing: 0.05
phase: train
save_interval: 10
eval_interval: 1
log_interval: 100
print_log: true
save_result: false
pavi_log: false
feeder: feeder.feeder.Feeder
num_worker: 0
train_feeder_args:
  data_path: data/basketball_processed/GAR/C4/train_data.npy
  label_path: data/basketball_processed/GAR/C4/train_label.pkl
  random_choose: false
  random_move: false
  window_size: 400
  debug: false
test_feeder_args:
  data_path: data/basketball_processed/GAR/C4/val_data.npy
  label_path: data/basketball_processed/GAR/C4/val_label.pkl
model: net.shift_dual_stgcn_backbone.Model
model_args:
  in_channels: 4
  num_class: 20
  num_point: 17
  num_person: 6
  graph_args:
    layout: sga_interact_17
    strategy: spatial
  in_channels_semantic: 1
  use_temporal_attention: true
  tag:
    enable: true
    mode: ball
    use_ball: true
    detach_adj: true
    norm: sym
    lambda_fuse: 0.05
    learnable_lambda: false
    self_loop: true
    ramp_epochs: 12
    tau: 0.35
    ball_mix: true
    ball_weight: 0.8
    ball_tau_center: 0.35
    soft_selector:
      enable: true
      k_list:
      - 2
      - 3
      - 4
      - 5
      selector: global
      warmup_epochs: 12
      gate_init: 0.0
      gate_max: 1.0
      temperature: 1.0
  backbone_cls: net.st_gcn.Model
  backbone_args:
    in_channels: 4
    num_class: 20
    edge_importance_weighting: true
    graph_args:
      layout: sga_interact_17
      strategy: spatial
  backbone_weights: ./work_dir/recognition/tag/ST_GCN_C4_processed/best_model.pt
  backbone_ignore: []
  freeze_backbone: true
  person_pool: mean
  kd:
    enable: false
    alpha: 0.0
    temperature: 2.0
  finetune_backbone: true
  unfreeze_backbone_last_k: 3
  backbone_train_bn: true
device:
- 0
batch_size: 16
test_batch_size: 8
num_epoch: 40
base_lr: 0.0005
weight_decay: 0.0005
step:
- 25
- 35
show_topk:
- 1
- 5
use_kd: false
kd_alpha: 0.0
kd_temperature: 4.0
